$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/AS22L_lite_pbase_ivi_mtk2712 -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_AS22L_lite_pbase_ivi_mtk2712 -H -P -S -G -W /workspace/xulun/opengrok/etc/AS22L_lite_pbase_ivi_mtk2712/configuration.xml -T 64 -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/AS22L_lite_pbase_ivi_mtk2712/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/AS22L_lite_pbase_ivi_mtk2712.war
# /workspace/xulun/alios/AS22L_lite_venus_dev
$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/AS22L_lite_venus_dev -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_AS22L_lite_venus_dev -H -P -S -G -W /workspace/xulun/opengrok/etc/AS22L_lite_venus_dev/configuration.xml -T 64 -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/AS22L_lite_venus_dev/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/AS22L_lite_venus_dev.war
# /workspace/xulun/alios/BMV1_lite_venus_dev
$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/BMV1_lite_venus_dev -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_BMV1_lite_venus_dev -H -P -S -G -W /workspace/xulun/opengrok/etc/BMV1_lite_venus_dev/configuration.xml -T 64 -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/BMV1_lite_venus_dev/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/BMV1_lite_venus_dev.war
$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/AS22L_baseos_dev -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_AS22L_baseos_dev -H -P -S -G -W /workspace/xulun/opengrok/etc/AS22L_baseos_dev/configuration.xml -T 64 -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i d:'test_data' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/AS22L_baseos_dev/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/AS22L_baseos_dev.war
# /workspace/xulun/alios/AS22_lite_venus_dev_zama
$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/AS22_lite_venus_dev_zama -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_AS22_lite_venus_dev_zama -H -P -S -G -W /workspace/xulun/opengrok/etc/AS22_lite_venus_dev_zama/configuration.xml -T 64 -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i d:'test_data' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/AS22_lite_venus_dev_zama/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/AS22_lite_venus_dev_zama.war
# /workspace/xulun/alios/pbase_ivi_rcarh3n
$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/pbase_ivi_rcarh3n -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_pbase_ivi_rcarh3n -H -P -S -G -W /workspace/xulun/opengrok/etc/pbase_ivi_rcarh3n/configuration.xml -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i d:'test_data' -i '*.json' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/pbase_ivi_rcarh3n/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/pbase_ivi_rcarh3n.war
# /workspace/xulun/alios/SWORD-1_lite_venus_dev
$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/SWORD-1_lite_venus_dev -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_SWORD-1_lite_venus_dev -H -P -S -G -W /workspace/xulun/opengrok/etc/SWORD-1_lite_venus_dev/configuration.xml -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i d:'test_data' -i '*.json' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/SWORD-1_lite_venus_dev/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/SWORD-1_lite_venus_dev.war
# /workspace/xulun/alios/AS22L_baseos_dev_gearv
$JAVA_HOME/bin/java -Djava.util.logging.config.file=/workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/etc/logging.properties -jar /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/opengrok.jar -c /workspace/xulun/github/ctags/ctags -s /workspace/xulun/alios/AS22L_baseos_dev_gearv -d /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/data_AS22L_baseos_dev_gearv -H -P -S -G -W /workspace/xulun/opengrok/etc/AS22L_baseos_dev_gearv/configuration.xml -T 64 -v -i '*.so' -i '*.patch' -i '*.jar' -i '*.crt' -i '*.pem' -i '*.s' -i '*.gz' -i d:'mozilla' -i d:'indexes' -i d:'test_data' -i '*.class' -i 'zh.xml'
opengrok-deploy -c /workspace/xulun/opengrok/etc/AS22L_baseos_dev_gearv/configuration.xml /workspace/xulun/gitlab/opengrok/distribution/target/opengrok-1.3.6/lib/source.war /root/apache-tomcat-9.0.30/webapps/AS22L_baseos_dev_gearv.war